version: 0.2

env:
  variables:
    DOCKER_USERNAME: "adaol"
    IMAGE_NAME: "simple-blog-kubernetes"
    IMAGE_TAG: "latest-frontend"
  secrets-manager:
    DOCKER_PASSWORD: "docker:password"

phases:
  install:
    commands:
      - export REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
  pre_build:
    commands:
      - cd ./frontend
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo pushing docker image...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG