version: 0.2

env:
  variables:
    DOCKER_USERNAME: "adaol"
    IMAGE_NAME: "simple-blog-kubernetes"
    IMAGE_TAG: "api-latest"
  secrets-manager:
    DOCKER_PASSWORD: "arn:aws:secretsmanager:us-east-1:081975665870:secret:docker_password-EHEGAM"

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo Build enviromment `uname -a` `aws --version 2>&1` `python --version`
      - echo Started build at `date`
      - pip install -r requirements.txt
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
      - python -m pytest
      - echo Building the Docker image...          
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG


  post_build:
    commands:
      - echo Finished build at `date`
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
